#!/usr/bin/python3
def raise_custom_exception(message=""):
    raise NameError(message)
